prompt = '  '

padding = 350

fonts = [
    'Symbols Nerd Font Mono',
    'Arimo Nerd Font'
]
font_size = 20.0

[history]
decrease_interval = 48

[colors]
background = '#000000CC'
prompt = '#FFFFFF'
text = '#696969'
text_query = '#FFFFFF'
text_selected = '#FFFFFF'

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
