# Does not work 
#
#[als.iio]
#path = "/sys/bus/iio/devices"
#thresholds = { 0 = "night", 20 = "dark", 80 = "dim", 250 = "normal", 500 = "bright", 800 = "outdoors" }

[als.webcam]
video = 0
thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wlroots"


[[keyboard]]
name = "keyboard"
path = "/sys/class/leds/asus::kbd_backlight"